### PR TITLE
id3v2 TXXX, UFID & PRIV tag support

### PR DESCRIPTION
**Pull request by Borewit**
Added support for a few new tags in id3v2 header:
TXXX "User defined text information frame"
UFID "Unique file identifier"
PRIV "Private frame"

TXXX & UFID are used by MusicBrainz.

### CODE REVIEW

**Comment by mainrs** [comment]
Looks neat. Any update on this? @leetreveil  @Borewit?

**Comment by Borewit** [comment]
Sure, code is hosted under a different [repo](https://github.com/Borewit/music-metadata) / [package](https://www.npmjs.com/package/music-metadata).

**Comment by mainrs** [comment]
@Borewit thanks! Any plans for the feature? Would love to contribute. I need a package that stays up-to-date :smile:

**Comment by Borewit** [comment]
Nice to get some enthusiastic response @SirWindfield,
You are welcome to contribute.

I have some ideas what could be done:
- Improve documentation:
  - Write detailed documentation on the GitHib Wiki how the tag mapping is done
- Re-factoring:
  - Move away from the readstream approach and use straight file access; stream is very inefficient in some cases (cannot jump to the end of the file, without reading everything in between) and cumbersome in my opinion. For instance, if a FLAC file prefixed with an id3 header (bad practice, non-standard, but it is done)  this code gets completely confused, beacuse it expects mpeg. 
  - Use promises
- Improve tests: 
  - use a test framework like [Mocha](https://mochajs.org/)
  - translate test case code to TypeScript
- New features / functionality:
  - In addition to MusicBrainz tags, support Discogs tags, maybe iTunes tags
  - Support audio CRC values
  - Report on errors
  - Be able to write tags

**Pull request closed without merging**
