### PR TITLE
Improved APE2 / MonkeyAudio support: added duration support

### PR DESCRIPTION
**Pull request by Borewit**
For future use, following is also decoded:
- bits per sample
- sample rate
- compressionLevel

### CODE REVIEW

**Comment by leetreveil** [comment]
Looks really good!

**Comment by Borewit** [comment]
I started deploy my own package yesterday (music-metadata), thought you fell of the earth 😉

Got many more changes in the pipeline. 

Added many more mappings, native tags, format info like sample rate, bits per sample etc. Mapping is also easier to manage.

But these changes will modify your existing API.

I am considering:
- to start moving to typescript
- extend the event callback: distinct between common (aliased), native and format callbacks
- have cross formats tests to ensure each format provides same info wherever feasible. For example, MP3 should not provide bits per sample, because this concept is non existing in its encoded format. But it should return a sample rate.

Let me know if you are interested in merging the whole thing

Bor

**Comment by leetreveil** [comment]
Had a quick look at your package, looks good! I'm probably not going to accept any major API changes to `musicmetdata` at this stage of maturity so forking and publishing your own package makes sense to me.

Would you consider renaming your package from `music-metadata` to something else? Folks could get confused with the extremely similar package names.

**Comment by Borewit** [comment]
Name is ugly close, sorry about that.

**Pull request merged**
