### PR TITLE
Requestjs compat

### PR DESCRIPTION
**Pull request by kf6kjg**
Now easy internet streams can determine the duration!

Thus far, after only gentle searching, I've not found any documented way to detect that the stream has what is needed.  So I cheated and used testing for the information I'm looking for.

I also didn't find documentation on the location of said information.  I simply threw the contents out to console.log and looked for it.

While using undocumented data is a bit risky, I found it to be very useful in my application. YMMV.

### CODE REVIEW

**Comment by leetreveil** [comment]
Hey, i'm not going to merge this, adding support for one type of http library doesn't make sense as it excludes all of the other libraries from the party.

One idea is to open up the API so the file size can be a callback:

```javascript
var fs = require('fs');
var mm = require('musicmetadata');
var request = require('request');

var webstream = request.get('http://www.example.com/some.mp3')

// create a new parser from a node ReadStream
var parser = mm(webstream, function (err, metadata) {
  if (err) throw err;
  console.log(metadata);
}, function (cb) {
  cb(webstream.responseContent.headers['content-length'])
});
```

I think this would work really well actually,

**Comment by kf6kjg** [comment]
Try doing it against a list of multiple files from the web, not just one.
I think you'll run across the same problem we are discussing in #97: loss
of context.  How would you determine which ```webstream``` the callback is
supposed to return data for?

Untested Example:
```
var fs = require('fs');
var mm = require('musicmetadata');
var request = require('request');

var files = [
 'http://www.example.com/some1.mp3',
 'http://www.example.com/some2.mp3',
 'http://www.example.com/some3.mp3',
 'http://www.example.com/some4.mp3',
]

var index = files.length
while (--index >= 0) {
  var webstream = request.get(files[index])

  // create a new parser from a node ReadStream
  var parser = mm(webstream, function (err, metadata) {
    if (err) throw err;
    console.log(metadata);
  }, function (cb) {
    cb(webstream.responseContent.headers['content-length'])
  });
}
```

Not having tested the above, relying instead on my mental JS
implementation, the above should result in ```webstream``` losing context:
you'll get, maybe, the last stream's length for all entries, or possibly
even nothing at all - I'd have to test to find out for certain.

**Comment by leetreveil** [comment]
Yeah exactly. This would work:


```javascript
var files = [
 'http://www.example.com/some1.mp3',
 'http://www.example.com/some2.mp3',
 'http://www.example.com/some3.mp3',
 'http://www.example.com/some4.mp3',
]

files.forEach(function (url) {
  var webstream = request.get(files[index])
  var parser = mm(webstream, function (err, metadata) {
    if (err) throw err;
    console.log(metadata);
  }, function (cb) {
    cb(webstream.responseContent.headers['content-length'])
  })
})
```

The reason? the `forEach` callback captures the url variable making it available to the second callback.

The reason your example wouldn't work is because by the time the `musicmetadata` callback has been called the while loop has already exhausted the list.

**Comment by icidasset** [comment]
Hi guys, so is there a way to use this library with http requests/streams? If not, I would like to work on this even though I don't know anything about node streams. Side note, I would like to use this library in the browser.

**Pull request closed without merging**
